In [1]:
import numpy as np

In [ ]:
#a = np.array([1,2,3,4,5])
a = np.array([1,2,3,4,5], dtype ='int16') # if we want to change int type we have to type it.
b = np.array([6,7,8,9,10])

print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [15]:
c = np.array([1,2,3,4,5,6,7,8,9])
d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
d.ndim

2

In [17]:
a.shape

(5,)

In [10]:
d.shape

(2, 5)

In [18]:
a.dtype

dtype('int16')

In [ ]:
a.itemsize #it's 2 because it's int 16. if it's int 32 it might become 4

2

In [20]:
b.itemsize

4

In [21]:
a.size

5

In [ ]:
a.nbytes # this is the total size.( multiplying size into itemsize)

10

In [23]:
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
d.shape

(2, 5)

Get a specific element [r,c]

In [34]:
d[1,2]

8

Get a specific row

In [35]:
d[0,:]

array([1, 2, 3, 4, 5])

Get a specific Column

In [36]:
d[:,2]

array([3, 8])

Getting a little more fancy [startindex: endindex: stepsize]

In [41]:
d[0, 1:5:2]

array([2, 4])

In [43]:
d[1,4] = 20
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]


In [45]:
d[:,2] = [1,2]
print(d)

[[ 1  2  1  4  5]
 [ 6  7  2  9 20]]


3-d Example

In [47]:
e = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [48]:
e[:,1,:]

array([[3, 4]])

In [54]:
e[0,1,1]

4

In [61]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2))  # you can also specify the data type. 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,2),19) # you can also specify the data type. 

array([[19, 19],
       [19, 19]])

In [68]:
np.full_like(d,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

Random decimal Number

In [69]:
np.random.rand(4,2)

array([[0.32416149, 0.33339703],
       [0.33464447, 0.99343289],
       [0.60421804, 0.90208092],
       [0.68302548, 0.19944989]])

In [70]:
np.random.randint(7)

5

In [71]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [78]:
r2 = np.repeat(arr,3,axis = 0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Important Question

In [85]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!

In [96]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics!!

In [97]:
a + 2

array([3, 4, 5])

In [91]:
a - 2

array([-1,  0,  1])

In [92]:
a * 2

array([2, 4, 6])

In [93]:
a / 2

array([0.5, 1. , 1.5])

In [98]:
a ** b

array([ 1,  4, 27])